source "https://rubygems.org"

# core processor
gem "asciidoctor", "~> 2.0.26"

# output converters
gem "asciidoctor-epub3", "~> 2.3.0"
gem "asciidoctor-html5s", "= 0.5.1"
gem "asciidoctor-multipage", "= 0.0.19"
gem "asciidoctor-pdf", "~> 2.3.24"
gem "asciidoctor-revealjs", "~> 5.2.0"

# document preprocessing and transformation
gem "asciidoctor-reducer", "~> 1.1.2"

# Asciidoctor extensions
gem "asciidoctor-bibtex", "~> 0.9.0"
gem "asciidoctor-kroki", "~> 1.0.0"
gem "asciidoctor-lists", "~> 1.1.2"
gem "asciidoctor-mathematical", "= 0.3.5"

# disabled extensions
# gem "asciidoctor-diagram", "~> 3.2.1"
# gem "asciidoctor-lists-extended", "~> 1.1.7"

# source-code syntax highlighters
gem "coderay", "~> 1.1.3"
gem "pygments.rb", "~> 4.0.0"
gem "rouge", "~> 4.7.0"

# PDF and image-processing support
gem "prawn-gmagick", "= 0.0.9"

# language-aware hyphenation
gem "text-hyphen", "~> 1.5.0"

# explicit runtime dependencies no longer bundled by Ruby
gem "base64", "~> 0.3.0"
gem "bigdecimal", "~> 3.1.8"
