source "https://rubygems.org"

# Asciidoctor core
gem "asciidoctor", "~> 2.0.26"

# Converters and command-line tools
gem "asciidoctor-pdf", "~> 2.3.24"
gem "asciidoctor-epub3", "~> 2.3.0"
gem "asciidoctor-multipage", "= 0.0.19"
gem "asciidoctor-reducer", "~> 1.1.2"
gem "asciidoctor-revealjs", "~> 5.2.0"

# Asciidoctor extensions
gem "asciidoctor-html5s", "= 0.5.1"
gem "asciidoctor-bibtex", "~> 0.9.0"
gem "asciidoctor-mathematical", "= 0.3.5"
gem "asciidoctor-kroki", "~> 1.0.0"
gem "asciidoctor-lists", "~> 1.1.2"
#gem "asciidoctor-lists-extended", "~> 1.1.7"
#gem "asciidoctor-diagram", "~> 3.2.1"

# Source-code highlighters supported by Asciidoctor
gem "coderay", "~> 1.1.3"
gem "pygments.rb", "~> 4.0.0"
gem "rouge", "~> 4.7.0"

# Faster image processing and additional image formats
gem "prawn-gmagick", "= 0.0.9"

# Automatic language-aware hyphenation
gem "text-hyphen", "~> 1.5.0"

gem "bigdecimal", "~> 3.1.8"
